--- #YAML:1.0
name:               Devel-Spy
version:            0.07
abstract:           Spy on your objects and data
author:
    - Joshua ben Jore <jjore@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    constant:        0
    overload:        0
    strict:          0
    Sub::Name:       0
    Test::Class:     0
    Test::More:      0
    Test::Warn:      0
    UNIVERSAL::ref:  0
    warnings:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
